// AUTO-GENERATED by tools/generate-behavior-docs.ts
// Do not edit manually. Re-run the generator after adding behaviors.
//
// Generated: 2026-03-22T02:18:56.715Z
// Total: 93 behaviors (50 atoms, 18 molecules, 25 organisms)

export const behaviorSidebarItems = [
  "reference/behaviors",
  {
    type: "category" as const,
    label: "Atoms (50)",
    collapsed: true,
    items: ["reference/behaviors/std-async", "reference/behaviors/std-browse", "reference/behaviors/std-cache-aside", "reference/behaviors/std-calendar", "reference/behaviors/std-circuit-breaker", "reference/behaviors/std-collision", "reference/behaviors/std-combat", "reference/behaviors/std-combat-log", "reference/behaviors/std-confirmation", "reference/behaviors/std-dialogue-box", "reference/behaviors/std-display", "reference/behaviors/std-drawer", "reference/behaviors/std-filter", "reference/behaviors/std-flip-card", "reference/behaviors/std-gallery", "reference/behaviors/std-game-audio", "reference/behaviors/std-game-canvas2d", "reference/behaviors/std-game-canvas3d", "reference/behaviors/std-game-hud", "reference/behaviors/std-game-menu", "reference/behaviors/std-game-over-screen", "reference/behaviors/std-gameflow", "reference/behaviors/std-input", "reference/behaviors/std-inventory-panel", "reference/behaviors/std-isometric-canvas", "reference/behaviors/std-loading", "reference/behaviors/std-modal", "reference/behaviors/std-movement", "reference/behaviors/std-notification", "reference/behaviors/std-overworld", "reference/behaviors/std-pagination", "reference/behaviors/std-physics2d", "reference/behaviors/std-platformer-canvas", "reference/behaviors/std-quest", "reference/behaviors/std-rate-limiter", "reference/behaviors/std-rating", "reference/behaviors/std-score", "reference/behaviors/std-score-board", "reference/behaviors/std-search", "reference/behaviors/std-selection", "reference/behaviors/std-simulation-canvas", "reference/behaviors/std-sort", "reference/behaviors/std-sprite", "reference/behaviors/std-tabs", "reference/behaviors/std-text-effects", "reference/behaviors/std-theme", "reference/behaviors/std-timer", "reference/behaviors/std-undo", "reference/behaviors/std-upload", "reference/behaviors/std-wizard"],
  },
  {
    type: "category" as const,
    label: "Molecules (18)",
    collapsed: true,
    items: ["reference/behaviors/std-builder-game", "reference/behaviors/std-cart", "reference/behaviors/std-classifier-game", "reference/behaviors/std-debugger-game", "reference/behaviors/std-detail", "reference/behaviors/std-event-handler-game", "reference/behaviors/std-form-advanced", "reference/behaviors/std-geospatial", "reference/behaviors/std-inventory", "reference/behaviors/std-list", "reference/behaviors/std-messaging", "reference/behaviors/std-negotiator-game", "reference/behaviors/std-platformer-game", "reference/behaviors/std-puzzle-game", "reference/behaviors/std-quiz", "reference/behaviors/std-sequencer-game", "reference/behaviors/std-simulator-game", "reference/behaviors/std-turn-based-battle"],
  },
  {
    type: "category" as const,
    label: "Organisms (25)",
    collapsed: true,
    items: ["reference/behaviors/std-api-gateway", "reference/behaviors/std-arcade-game", "reference/behaviors/std-booking-system", "reference/behaviors/std-cicd-pipeline", "reference/behaviors/std-cms", "reference/behaviors/std-coding-academy", "reference/behaviors/std-crm", "reference/behaviors/std-devops-dashboard", "reference/behaviors/std-ecommerce", "reference/behaviors/std-finance-tracker", "reference/behaviors/std-healthcare", "reference/behaviors/std-helpdesk", "reference/behaviors/std-hr-portal", "reference/behaviors/std-iot-dashboard", "reference/behaviors/std-lms", "reference/behaviors/std-logic-training", "reference/behaviors/std-platformer-app", "reference/behaviors/std-project-manager", "reference/behaviors/std-puzzle-app", "reference/behaviors/std-realtime-chat", "reference/behaviors/std-rpg-game", "reference/behaviors/std-social-feed", "reference/behaviors/std-stem-lab", "reference/behaviors/std-strategy-game", "reference/behaviors/std-trading-dashboard"],
  },
  "reference/standard-library",
];
