/**
 * Register Orb language with Prism for Docusaurus.
 *
 * Registry-driven: imports tokens.json from @almadar/syntax which was
 * generated from @almadar/operators, @almadar/patterns, and @almadar/core.
 * When those registries are updated, rebuild @almadar/syntax and the
 * highlighting updates automatically.
 */

import siteConfig from '@generated/docusaurus.config';
import { registerLoloLanguage } from '@almadar/syntax';

// tokens.json is generated by @almadar/syntax from live registries
// eslint-disable-next-line @typescript-eslint/no-require-imports
const tokens = require('@almadar/syntax/tokens.json');

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function wordsToAlternation(words: string[]): string {
  return [...words].sort((a, b) => b.length - a.length).map(escapeRegex).join('|');
}

export default function prismIncludeLanguages(PrismObject: Record<string, unknown>): void {
  const {
    themeConfig: { prism },
  } = siteConfig;
  const { additionalLanguages } = prism as { additionalLanguages: string[] };

  (globalThis as Record<string, unknown>).Prism = PrismObject;
  additionalLanguages.forEach((lang: string) => {
    try {
      require(`prismjs/components/prism-${lang}`);
    } catch { /* skip */ }
  });

  const languages = (PrismObject as { languages: Record<string, unknown> }).languages;
  const extendFn = languages.extend as (id: string, redef: Record<string, unknown>) => Record<string, unknown>;

  console.log('[orb-syntax] Prism.languages available:', Object.keys(languages).filter(k => !k.startsWith('_')).join(', '));
  console.log('[orb-syntax] extend function exists:', typeof extendFn);

  const insertBefore = languages.insertBefore as (inside: string, before: string, insert: Record<string, unknown>, root?: Record<string, unknown>) => Record<string, unknown>;

  if (typeof extendFn === 'function' && typeof insertBefore === 'function') {
    // Start with a copy of JSON grammar
    languages.orb = extendFn.call(languages, 'json', {});

    // Build patterns from registry data
    const effectOps = wordsToAlternation(tokens.effectTypes);
    const slots = wordsToAlternation(tokens.uiSlots);
    const fieldTypes = wordsToAlternation(tokens.fieldTypes);
    const persistence = wordsToAlternation(tokens.persistenceKinds);
    const structural = wordsToAlternation(tokens.structuralKeys);
    const patternAlt = tokens.patternNames.length > 0 ? wordsToAlternation(tokens.patternNames) : null;
    const behaviors = tokens.behaviorNames.length > 0 ? wordsToAlternation(tokens.behaviorNames) : null;

    // Per-namespace operator patterns
    const nsPatterns: Record<string, unknown> = {};
    for (const [ns, ops] of Object.entries(tokens.operatorsByNamespace)) {
      const opList = ops as string[];
      if (opList.length > 0) {
        nsPatterns[`orb-op-${ns}`] = {
          pattern: new RegExp(`"(?:${wordsToAlternation(opList)})"`, ''),
          greedy: true,
        };
      }
    }

    // insertBefore places these tokens BEFORE "property" in the grammar,
    // so they match before the generic "string" and "property" patterns.
    insertBefore('orb', 'property', {
      // Bindings (highest priority)
      'orb-binding': {
        pattern: /"@(?:entity|payload|state|now|config|computed|trait)(?:\.[a-zA-Z0-9_.]+)?"/,
        greedy: true,
      },
      'orb-entity-ref': {
        pattern: /"@[A-Z][a-zA-Z0-9]*(?:\.[a-zA-Z0-9_.]+)?"/,
        greedy: true,
      },

      // Structural keys (followed by colon) - must match before property
      'orb-structural': {
        pattern: new RegExp(`"(?:${structural})"\\s*:`, ''),
        greedy: true,
      },

      // Effect operators (from registry)
      'orb-effect': {
        pattern: new RegExp(`"(?:${effectOps})"`, ''),
        greedy: true,
      },

      // Events: UPPER_SNAKE_CASE
      'orb-event': {
        pattern: /"[A-Z][A-Z0-9_]{2,}"/,
        greedy: true,
      },

      // UI slots
      'orb-slot': {
        pattern: new RegExp(`"(?:${slots})"`, ''),
        greedy: true,
      },

      // Field types
      'orb-field-type': {
        pattern: new RegExp(`"(?:${fieldTypes})"`, ''),
        greedy: true,
      },

      // Persistence kinds
      'orb-persistence': {
        pattern: new RegExp(`"(?:${persistence})"`, ''),
        greedy: true,
      },

      // Pattern names (from @almadar/patterns registry)
      ...(patternAlt ? {
        'orb-pattern': {
          pattern: new RegExp(`"(?:${patternAlt})"`, ''),
          greedy: true,
        },
      } : {}),

      // Standard behaviors
      ...(behaviors ? {
        'orb-behavior': {
          pattern: new RegExp(`"(?:${behaviors})"`, ''),
          greedy: true,
        },
      } : {}),

      // Operators by namespace
      ...nsPatterns,
    });
  }

  // Register lolo language
  registerLoloLanguage(PrismObject);

  console.log('[orb-syntax] orb language registered:', !!languages.orb);
  console.log('[orb-syntax] lolo language registered:', !!languages.lolo);

  delete (globalThis as Record<string, unknown>).Prism;
}
