'use client';
/**
 * Card Component
 *
 * A generic card container for displaying content with optional title,
 * subtitle, and action buttons.
 *
 * @generated by Orbital Compiler
 */

import React from "react";
import { useEventBus } from "../../hooks/useEventBus";

export interface CardAction {
  label: string;
  onClick?: () => void;
  /** Event name to emit when clicked (for trait state machine integration) */
  event?: string;
  variant?: "default" | "primary" | "danger";
  icon?: string;
  disabled?: boolean;
}

export interface CardProps {
  /** Card title */
  title?: string;
  /** Card subtitle or description */
  subtitle?: string;
  /** Image URL to display at top of card */
  image?: string;
  /** Action buttons to display in card footer */
  actions?: CardAction[];
  /** Card content */
  children?: React.ReactNode;
  /** Click handler for the entire card */
  onClick?: () => void;
  /** Additional CSS classes */
  className?: string;
  /** Declarative event name — emits UI:{action} via eventBus on card click */
  action?: string;
}

/**
 * Card component for displaying content in a contained box
 */
export function Card({
  title,
  subtitle,
  image,
  actions,
  children,
  onClick,
  className = "",
  action,
}: CardProps) {
  const eventBus = useEventBus();
  const isClickable = !!onClick || !!action;

  const handleClick = () => {
    if (action) eventBus.emit(`UI:${action}`, {});
    onClick?.();
  };

  return (
    <div
      className={`
        bg-[var(--color-card)]
        border border-[var(--color-border)]
        rounded-[var(--radius-md)] shadow-[var(--shadow-sm)]
        ${isClickable ? "cursor-pointer hover:shadow-[var(--shadow-hover)] transition-shadow" : ""}
        ${className}
      `}
      onClick={isClickable ? handleClick : undefined}
      role={isClickable ? "button" : undefined}
      tabIndex={isClickable ? 0 : undefined}
      onKeyDown={
        isClickable ? (e) => e.key === "Enter" && handleClick() : undefined
      }
    >
      {/* Image */}
      {image && (
        <div className="aspect-video w-full overflow-hidden rounded-t-lg">
          <img
            src={image}
            alt={title || "Card image"}
            className="w-full h-full object-cover"
          />
        </div>
      )}

      {/* Content */}
      <div className="p-4">
        {/* Header */}
        {(title || subtitle) && (
          <div className="mb-3">
            {title && (
              <h3 className="text-lg font-semibold text-[var(--color-card-foreground)]">
                {title}
              </h3>
            )}
            {subtitle && (
              <p className="text-sm text-[var(--color-muted-foreground)] mt-1">
                {subtitle}
              </p>
            )}
          </div>
        )}

        {/* Children */}
        {children && (
          <div className="text-[var(--color-card-foreground)]">{children}</div>
        )}

        {/* Actions */}
        {actions && actions.length > 0 && (
          <div className="flex flex-wrap gap-2 mt-4 pt-4 border-t border-[var(--color-border)]">
            {actions.map((action, index) => (
              <button
                key={index}
                onClick={(e) => {
                  e.stopPropagation();
                  if (action.event) eventBus.emit(`UI:${action.event}`, { label: action.label });
                  action.onClick?.();
                }}
                disabled={action.disabled}
                className={`
                  px-3 py-1.5 text-sm font-medium rounded-[var(--radius-sm)]
                  transition-colors
                  ${
                    action.variant === "primary"
                      ? "bg-[var(--color-primary)] text-[var(--color-primary-foreground)] hover:bg-[var(--color-primary-hover)] disabled:opacity-50"
                      : action.variant === "danger"
                        ? "bg-[var(--color-error)] text-[var(--color-error-foreground)] hover:opacity-90 disabled:opacity-50"
                        : "bg-[var(--color-muted)] text-[var(--color-foreground)] hover:bg-[var(--color-surface-hover)]"
                  }
                  disabled:cursor-not-allowed
                `}
              >
                {action.label}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

Card.displayName = 'Card';

export default Card;
