#!/usr/bin/env tsx
/**
 * generate-behavior-catalog.ts
 *
 * Build `src/data/behavior-catalog.ts` from the `@almadar/std` source tree
 * in the main monorepo. Reads:
 *   - behaviors/registry/{atoms,molecules,organisms}/std-X.orb   (schema JSON)
 *   - behaviors/functions/{atoms,molecules,organisms}/std-X.ts   (source wrapper)
 *   - behaviors/lolo/{atoms,molecules,organisms}/std-X.lolo      (canonical .lolo source)
 *
 * Usage (from almadar/orb/):
 *   npx tsx scripts/generate-behavior-catalog.ts
 *
 * Override the std source path via STD_ROOT env var. Default assumes the
 * monorepo layout at ~/kflow.ai.builder/packages/almadar-std.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import { homedir } from 'node:os';

/**
 * Run `orbital resolve` on an .orb to inline every trait / entity / page
 * reference. OrbPreview's client-side `schemaToIR` does NOT preprocess
 * `uses` imports, so a trait like `ListItemCreate = Modal.traits.
 * ModalRecordModal` arrives with `ref:` but no `stateMachine` — which
 * means the playground's state machine never sees its transitions and
 * events like CREATE dispatch but have no listener.
 *
 * We shell out to the installed `orbital` binary (same one that runs
 * `phase-9-compile-all.sh`) so the resolver stays in one place and
 * preview schemas match what the server-side runtime would see after
 * `preprocessSchema`.
 */
const ORBITAL_BIN = process.env.ORBITAL_BIN ?? join(homedir(), 'bin/orbital');

function resolveOrbJson(orbPath: string, fallback: string): string {
  if (!existsSync(ORBITAL_BIN)) {
    return fallback;
  }
  try {
    return execFileSync(ORBITAL_BIN, ['resolve', orbPath], {
      encoding: 'utf8',
      maxBuffer: 32 * 1024 * 1024,
    });
  } catch (err) {
    console.warn(
      `${orbPath}: orbital resolve failed, using raw .orb — ${
        (err as Error).message
      }`,
    );
    return fallback;
  }
}

const ORB_ROOT = resolve(__dirname, '..');
const STD_ROOT =
  process.env.STD_ROOT ||
  resolve(ORB_ROOT, '../../packages/almadar-std');

if (!existsSync(STD_ROOT)) {
  console.error(`std source tree not found at ${STD_ROOT}`);
  console.error(`set STD_ROOT to the @almadar/std checkout path`);
  process.exit(1);
}

type Level = 'atom' | 'molecule' | 'organism';
const TIERS: { dir: string; level: Level }[] = [
  { dir: 'atoms', level: 'atom' },
  { dir: 'molecules', level: 'molecule' },
  { dir: 'organisms', level: 'organism' },
];

interface Entry {
  name: string;
  description: string;
  level: Level;
  schema: string;
  source: string;
  lolo: string;
}

function escapeTemplateLiteral(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function readIfExists(path: string): string {
  return existsSync(path) ? readFileSync(path, 'utf8') : '';
}

const entries: Entry[] = [];

for (const { dir, level } of TIERS) {
  const regDir = join(STD_ROOT, 'behaviors/registry', dir);
  const fnDir = join(STD_ROOT, 'behaviors/functions', dir);
  const loloDir = join(STD_ROOT, 'behaviors/lolo', dir);
  if (!existsSync(regDir)) continue;

  for (const file of readdirSync(regDir).sort()) {
    if (!file.endsWith('.orb')) continue;
    const name = file.slice(0, -'.orb'.length);

    const orbPath = join(regDir, file);
    const orbRaw = readFileSync(orbPath, 'utf8');
    // Fully inline trait/entity/page refs so the browser-side
    // `schemaToIR` sees every trait with its `stateMachine`. The raw .orb
    // from the registry contains `{ ref: "Modal.traits.X" }` for imports;
    // OrbPreview can't resolve those without a `uses` loader, so the
    // preview traits end up with empty state machines and events go
    // nowhere. Running `orbital resolve` here produces the same shape
    // the server-side `preprocessSchema` would.
    const resolved = resolveOrbJson(orbPath, orbRaw);
    let schemaObj: unknown;
    try {
      schemaObj = JSON.parse(resolved);
    } catch (err) {
      console.error(`${name}: JSON parse failed — ${(err as Error).message}`);
      continue;
    }
    const description =
      (schemaObj as { description?: string } | undefined)?.description ?? name;

    const source = readIfExists(join(fnDir, `${name}.ts`));
    const lolo = readIfExists(join(loloDir, `${name}.lolo`));

    entries.push({
      name,
      description,
      level,
      schema: JSON.stringify(schemaObj),
      source,
      lolo,
    });
  }
}

entries.sort((a, b) => a.name.localeCompare(b.name));

const header = `// AUTO-GENERATED by scripts/generate-behavior-catalog.ts
// Do not edit manually. Re-run the generator after updating @almadar/std:
//   npx tsx scripts/generate-behavior-catalog.ts
//
// Source:
//   behaviors/registry/{atoms,molecules,organisms}/std-X.orb   (schema)
//   behaviors/functions/{atoms,molecules,organisms}/std-X.ts   (source)
//   behaviors/lolo/{atoms,molecules,organisms}/std-X.lolo      (lolo)

// schema is typed as \`unknown\` because the .orb JSON uses \`payload\` on events
// while core's \`Event\` interface uses \`payloadSchema\` (a known mismatch
// validated by \`orbital validate\`, not the core types). Consumers cast the
// shape at the OrbPreview boundary.

export interface BehaviorEntry {
  schema: unknown;
  source: string;
  lolo: string;
  level: "atom" | "molecule" | "organism";
  name: string;
  description: string;
}

export const BEHAVIOR_CATALOG: Record<string, BehaviorEntry> = {
`;

const body = entries
  .map((e) => {
    return `  ${JSON.stringify(e.name)}: {
    name: ${JSON.stringify(e.name)},
    description: ${JSON.stringify(e.description)},
    level: ${JSON.stringify(e.level)},
    schema: ${e.schema},
    source: \`${escapeTemplateLiteral(e.source)}\`,
    lolo: \`${escapeTemplateLiteral(e.lolo)}\`,
  },`;
  })
  .join('\n');

const footer = '\n};\n';

const out = header + body + footer;
const outPath = join(ORB_ROOT, 'src/data/behavior-catalog.ts');
writeFileSync(outPath, out);

console.log(`Wrote ${outPath}`);
console.log(`Total: ${entries.length} behaviors`);
const byLevel = entries.reduce<Record<string, number>>((acc, e) => {
  acc[e.level] = (acc[e.level] ?? 0) + 1;
  return acc;
}, {});
for (const [k, v] of Object.entries(byLevel)) console.log(`  ${k}: ${v}`);
