/**
 * Dynamic playground catalog loaders.
 *
 * The catalog assets are generated by `almadar-sync orb-website` into
 * `static/playground/` from the installed `@almadar/std` package. The
 * playground fetches them on demand instead of bundling one giant TS file.
 */

export interface BehaviorIndexEntry {
  name: string;
  description: string;
  level: 'atom' | 'molecule' | 'organism';
  topic: string;
}

export interface BehaviorDetail extends BehaviorIndexEntry {
  schema: unknown;
  source: string;
  lolo: string;
}

export type ModuleCatalog = Record<
  string,
  Record<string, { description: string; example: string; returnType: string }>
>;

const BASE = '/playground';

export async function loadBehaviorIndex(): Promise<BehaviorIndexEntry[]> {
  const res = await fetch(`${BASE}/behaviors/index.json`);
  if (!res.ok) {
    throw new Error(`Failed to load behavior index: ${res.status}`);
  }
  return (await res.json()) as BehaviorIndexEntry[];
}

export async function loadBehavior(name: string): Promise<BehaviorDetail> {
  const res = await fetch(`${BASE}/behaviors/${encodeURIComponent(name)}.json`);
  if (!res.ok) {
    throw new Error(`Failed to load behavior ${name}: ${res.status}`);
  }
  return (await res.json()) as BehaviorDetail;
}

export async function loadModules(): Promise<ModuleCatalog> {
  const res = await fetch(`${BASE}/modules.json`);
  if (!res.ok) {
    throw new Error(`Failed to load modules: ${res.status}`);
  }
  return (await res.json()) as ModuleCatalog;
}
